---
# tasks file for nginx
# roles/nginx_webapp/tasks/main.yml

- name: Install Docker
  yum:
    name: docker
    state: present

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Create directory for web app
  file:
    path: "{{ webapp_path }}"
    state: directory

- name: Copy web app files to master node
  copy:
    src: /home/ec2-user/index.html
    dest: "{{ webapp_path }}"
    remote_src: yes
  delegate_to: 107.21.188.86  # Ensure the file is copied to the master node

- name: Build Nginx Docker image on master node
  docker_image:
    name: "{{ docker_image_name }}"
    source: build
    build:
      path: "{{ dockerfile_path }}"
  delegate_to: 107.21.188.86  # Build the Docker image on the master node

- name: Log in to Docker Hub
  command: "docker login -u prasathvishnu2@gmail.com -p Pavini94@"

- name: Push Docker image to registry
  docker_image:
    name: "{{ docker_image_name }}"
    push: yes
  delegate_to: 107.21.188.86  # Push the Docker image from the master node

- name: Pull Docker image on master node
  docker_image:
    name: "{{ docker_image_name }}"
    source: pull
  delegate_to: 107.21.188.86  # Pull the Docker image on the master node

- name: Pull Docker image on slave nodes
  docker_image:
    name: "{{ docker_image_name }}"
    source: pull

- name: Run Nginx container on master node
  docker_container:
    name: "{{ container_name }}"
    image: "{{ docker_image_name }}"
    state: started
    restart_policy: always
    ports: "{{ container_ports }}"
  delegate_to: 107.21.188.86  # Run the Docker container on the master node

- name: Run Nginx container on slave nodes
  docker_container:
    name: "{{ container_name }}"
    image: "{{ docker_image_name }}"
    state: started
    restart_policy: always
    ports: "{{ container_ports }}"
