---
# tasks file for nginx
# roles/nginx_webapp/tasks/main.yml

- name: Install Docker
  yum:
    name: docker
    state: present

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Create directory for web app
  file:
    path: "{{ webapp_path }}"
    state: directory

- name: Copy web app files
  copy:
    src: /home/ec2-user/index.html
    dest: "{{ webapp_path }}"
    remote_src: yes

- name: Install python3-pip
  yum:
    name: python3-pip
    state: present

- name: Install virtualenv
  pip:
    name: virtualenv
    executable: /usr/bin/pip3
    state: present

- name: Create a virtual environment for Docker SDK
  command: "python3 -m virtualenv {{ docker_venv_path }}"
  args:
    creates: "{{ docker_venv_path }}"

- name: Install Docker SDK for Python in virtual environment
  pip:
    executable: "{{ docker_venv_path }}/bin/pip"
    name: docker
    version: "4.4.4"  # Specify version compatible with Python 2.7
    state: present

- name: Activate virtual environment
  shell: source {{ docker_venv_path }}/bin/activate

- name: Build Nginx Docker image
  docker_image:
    name: "{{ docker_image_name }}"
    source: build
    build:
      path: "{{ dockerfile_path }}"

- name: Run Nginx container
  docker_container:
    name: "{{ container_name }}"
    image: "{{ docker_image_name }}"
    state: started
    restart_policy: always
    ports: "{{ container_ports }}"
