---
# tasks file for nginx
# roles/nginx_webapp/tasks/main.yml

- name: Install Docker
  yum:
    name: docker
    state: present

- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes

- name: Create directory for web app
  file:
    path: "{{ webapp_path }}"
    state: directory

- name: Copy web app files
  copy:
    src: /home/ec2-user/index.html
    dest: "{{ webapp_path }}"
    remote_src: yes

- name: Install pip for Python 2.7
  yum:
    name: python-pip
    state: present

- name: Install virtualenv for Python 2.7
  pip:
    name: virtualenv
    executable: /usr/bin/pip
    state: present

- name: Create a virtual environment for Docker SDK
  command: "virtualenv {{ docker_venv_path }}"
  args:
    creates: "{{ docker_venv_path }}"

- name: Activate virtual environment for Docker SDK
  shell: source {{ docker_venv_path }}/bin/activate

- name: Install Docker SDK for Python in virtual environment
  pip:
    name: docker==4.4.4
    executable: "{{ docker_venv_path }}/bin/pip"
    state: present

- name: Build Nginx Docker image
  command: "docker build -t {{ docker_image_name }} {{ dockerfile_path }}"
  args:
    chdir: "{{ dockerfile_path }}"

- name: Run Nginx container
  command: "sudo docker run -itd --name {{ container_name }} -p 80:80 {{ docker_image_name }}"
